make healthcare resources explicitly depend on project module to finish (#785)
The current behavior is healthcare module resources will start being
created once the project itself is created and project ID is availale.
This can cause race condition between other resources such as api
identities and fhir store. FHIR store creation should wait for
healthcare api identity permission granting to finish, which is done as
part of the project factory module.

Sample error message is:
Error: Error creating FhirStore: googleapi: Error 403: failed to verify
dataset (projectID:..., datasetID:...),
please add the required bigquery.dataEditor and bigquery.jobUser roles
to your project's service account